server:
  port: ${PORT}

spring:
  config:
    import: ${AWS_NAME_SECRET_MANAGER}
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

entrypoint:
  sqs:
    region: ${SQS_LISTENER_REGION}
    queueUrl: ${SQS_DEBT_CAPACITY_LISTENER}

adapter:
  restconsumer:
    timeout: ${REST_CONSUMER_TIMEOUT}
    url: ${REST_CONSUMER_URL}

  sqs:
    region: ${SQS_SENDER_REGION}
    queueNotificationUrl: ${QUEUE_NOTIFICATION_URL_SEND}
    queueDebtCapacity: ${QUEUE_DEBT_CAPACITY_URL_SEND}
    queueIncreaseReport: ${QUEUE_INCREASE_REPORT}

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY}