server:
  servlet:
    context-path: /requests
  port: 8081

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/requests?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: 1234

adapter:
  restconsumer:
    timeout: 5000
    url: http://localhost:8080

  sqs:
    region: "us-east-1"
    queueNotificationUrl: "https://sqs.us-east-1.amazonaws.com/119694354572/poller-notifications"
    queueDebtCapacity: "https://sqs.us-east-1.amazonaws.com/119694354572/receive-debt-capacity"
    queueIncreaseReport: "https://sqs.us-east-1.amazonaws.com/119694354572/reports-listener"

entrypoint:
  sqs:
    region: "us-east-1"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/119694354572/send-debt-capacity"

cors:
  allowed-origins: http://localhost:4200,http://localhost:8080

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY}