spring:
  application:
    name: "requests"
  devtools:
    add-properties: false
  profiles:
    active: "${PROFILE:dev}"
    include: null
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      base-path: /requests/actuator
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"



routes:
  paths:
    loans: "/requests/api/v1/loans"
    loansById: "/requests/api/v1/loans/{id}"
springdoc:
  swagger-ui:
    path: "/requests/openapi/swagger-ui"
  api-docs:
    path: "/requests/openapi/v3/api-docs"
  packages-to-scan:
  - "co.com.crediya"
  paths-to-match:
  - "/**"

entrypoint:
  sqs:
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
