spring:
  config:
    import: ${AWS_NAME_SECRET_MANAGER}
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


adapter:
  restconsumer:
    timeout: ${REST_CONSUMER_TIMEOUT}
    url: ${REST_CONSUMER_URL}

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY}